/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortaisRouteImport } from './routes/portais'
import { Route as NegociosRouteImport } from './routes/negocios'
import { Route as MeuSiteRouteImport } from './routes/meu-site'
import { Route as LeadsInboxRouteImport } from './routes/leads-inbox'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConteudoIaRouteImport } from './routes/conteudo-ia'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisCadastrarRouteImport } from './routes/imoveis.cadastrar'

const PortaisRoute = PortaisRouteImport.update({
  id: '/portais',
  path: '/portais',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosRoute = NegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuSiteRoute = MeuSiteRouteImport.update({
  id: '/meu-site',
  path: '/meu-site',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsInboxRoute = LeadsInboxRouteImport.update({
  id: '/leads-inbox',
  path: '/leads-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoIaRoute = ConteudoIaRouteImport.update({
  id: '/conteudo-ia',
  path: '/conteudo-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisCadastrarRoute = ImoveisCadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => ImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contatos': typeof ContatosRoute
  '/conteudo-ia': typeof ConteudoIaRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/leads': typeof LeadsRoute
  '/leads-inbox': typeof LeadsInboxRoute
  '/meu-site': typeof MeuSiteRoute
  '/negocios': typeof NegociosRoute
  '/portais': typeof PortaisRoute
  '/imoveis/cadastrar': typeof ImoveisCadastrarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contatos': typeof ContatosRoute
  '/conteudo-ia': typeof ConteudoIaRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/leads': typeof LeadsRoute
  '/leads-inbox': typeof LeadsInboxRoute
  '/meu-site': typeof MeuSiteRoute
  '/negocios': typeof NegociosRoute
  '/portais': typeof PortaisRoute
  '/imoveis/cadastrar': typeof ImoveisCadastrarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contatos': typeof ContatosRoute
  '/conteudo-ia': typeof ConteudoIaRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/leads': typeof LeadsRoute
  '/leads-inbox': typeof LeadsInboxRoute
  '/meu-site': typeof MeuSiteRoute
  '/negocios': typeof NegociosRoute
  '/portais': typeof PortaisRoute
  '/imoveis/cadastrar': typeof ImoveisCadastrarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/contatos'
    | '/conteudo-ia'
    | '/contratos'
    | '/dashboard'
    | '/imoveis'
    | '/leads'
    | '/leads-inbox'
    | '/meu-site'
    | '/negocios'
    | '/portais'
    | '/imoveis/cadastrar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/contatos'
    | '/conteudo-ia'
    | '/contratos'
    | '/dashboard'
    | '/imoveis'
    | '/leads'
    | '/leads-inbox'
    | '/meu-site'
    | '/negocios'
    | '/portais'
    | '/imoveis/cadastrar'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/contatos'
    | '/conteudo-ia'
    | '/contratos'
    | '/dashboard'
    | '/imoveis'
    | '/leads'
    | '/leads-inbox'
    | '/meu-site'
    | '/negocios'
    | '/portais'
    | '/imoveis/cadastrar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ContatosRoute: typeof ContatosRoute
  ConteudoIaRoute: typeof ConteudoIaRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  LeadsInboxRoute: typeof LeadsInboxRoute
  MeuSiteRoute: typeof MeuSiteRoute
  NegociosRoute: typeof NegociosRoute
  PortaisRoute: typeof PortaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portais': {
      id: '/portais'
      path: '/portais'
      fullPath: '/portais'
      preLoaderRoute: typeof PortaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios': {
      id: '/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof NegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-site': {
      id: '/meu-site'
      path: '/meu-site'
      fullPath: '/meu-site'
      preLoaderRoute: typeof MeuSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-inbox': {
      id: '/leads-inbox'
      path: '/leads-inbox'
      fullPath: '/leads-inbox'
      preLoaderRoute: typeof LeadsInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo-ia': {
      id: '/conteudo-ia'
      path: '/conteudo-ia'
      fullPath: '/conteudo-ia'
      preLoaderRoute: typeof ConteudoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/cadastrar': {
      id: '/imoveis/cadastrar'
      path: '/cadastrar'
      fullPath: '/imoveis/cadastrar'
      preLoaderRoute: typeof ImoveisCadastrarRouteImport
      parentRoute: typeof ImoveisRoute
    }
  }
}

interface ImoveisRouteChildren {
  ImoveisCadastrarRoute: typeof ImoveisCadastrarRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisCadastrarRoute: ImoveisCadastrarRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ContatosRoute: ContatosRoute,
  ConteudoIaRoute: ConteudoIaRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  LeadsRoute: LeadsRoute,
  LeadsInboxRoute: LeadsInboxRoute,
  MeuSiteRoute: MeuSiteRoute,
  NegociosRoute: NegociosRoute,
  PortaisRoute: PortaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
